"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _github_activity from './github-activity.bones.json'

configureBoneyard({"color":"#272727","darkColor":"#272727","animate":"shimmer","shimmerColor":"#323232","darkShimmerColor":"#323232","speed":"1.8s","shimmerAngle":110,"stagger":80,"transition":300})

registerBones({
  "github-activity": _github_activity,
})
